### ISSUE TITLE
Colocar titulo do site, curta introdução e modo de visualização.

### ISSUE THREAD

**Issue by camilacarvalho** [jadsonluan/moodtracker#1]
https://github.com/jadsonluan/moodtracker/blob/2cc2f839b5ef61db01d9f7fd58465e5e61edfdbf/index.html#L8

Antes de qualquer coisa, queria dizer que amei a idéia e o html mesmo você dizendo que pretende melhorá-lo. Ele é tão colorido e feliz que acho que quem for usar o site vai acabar colocando sempre a tag de felicidade rsrsrs. Queria deixar uma pequena sugestão quanto a tela principal. Seria interessante colocar o nome do site nela. Você mencionou no README que Mood Tracking é a técnica, não sei se o site se chamará assim, mas de qualquer forma seria interessante o nome aparecer até para deixar sua marca registrada. Como o site é bem diferente do comum (sites de venda, redes sociais ... ), acredito que vale deixar uma pequena informação sobre o objetivo do site. Fiquei em dúvida quanto a seção de Visualizações. Se está se refere ao modo como o usuário irá visualizar os humores cadastrados, acho que não está tão sugestivo. Acredito que deveria vir em cima e talvez com um select ou radio, não sei.

**Comment by jadsonluan** [comment]
Oi, @camilacarvalho ! Implementei um cabeçalho na aplicação e reorganizei o layout. Quanto ao nome, acredito que vou deixar MoodTracker mesmo.

Logo mais eu vou melhorar a introdução e adicionar as visualizações.

Valeu pelas sugestões. :heart:
