### ISSUE TITLE
Personalizando

### ISSUE THREAD

**Issue by herculesra** [jadsonluan/moodtracker#2]
Uma imagem/logo seria excelente para dar "cara" ao projeto. =)

**Comment by jadsonluan** [comment]
Oi, @herculesra ! Desculpa a demora para responder aqui. :)

Eu ainda estou na busca por uma logo bonitinha para usar como favicon e dar uma identidade à ele. 

Muito obrigado pela sugestão! Abraços. :hugs:

**Comment by jadsonluan** [comment]
Depois de meses e várias jornadas consegui encontrar um favicon para aplicação! Adicionei nesse [commit](https://github.com/jadsonluan/moodtracker/commit/3ec81deda5dab813f920ea08ced4e1a282143f69)

Não achei algum objeto pra representar bem então optei por usar o "M" de MoodTracker usando a principal fonte e cor da aplicação

![image](https://user-images.githubusercontent.com/13488025/100686763-bfeeb780-335d-11eb-8e28-ad19322871c2.png)
