### ISSUE TITLE
Erro ao clicar no botão com campos vazios.

### ISSUE THREAD

**Issue by eduhique** [jadsonluan/moodtracker#3]
Considerei o "caminho feliz" (todos os parâmetros validos) para minha avaliação. Mas passando só para lembrar de tratar possíveis erros do usuário ao usar a aplicação.
https://github.com/jadsonluan/moodtracker/blob/5ad70078ae296512841e727c010c34c809edf21d/frontend/src/components/MoodForm/index.js#L44-L47

**Comment by jadsonluan** [comment]
Oi, @eduhique ! Eu implementei o tratamento de erros nos formulários agora a pouco. 

Valeu pelo feedback. :fist_oncoming:
