### ISSUE TITLE
Adicionar campo de texto para nova tag

### ISSUE THREAD

**Issue by lucasmedeiros** [jadsonluan/moodtracker#4]
![image](https://user-images.githubusercontent.com/19390820/95674155-ad89a600-0b84-11eb-9c6c-48a6d9539d64.png)

Ao clicar em "+ tags", apenas uma nova tag `Test` é criada. Acho que poderia ter um campo de texto logo abaixo das tags (e o botão de submeter também ficaria abaixo, do lado direito desse input) para o usuário escolher o nome da tag a adicionar. Se esse campo não for preenchido, não fazer nada.

O que acha?

**Comment by jadsonluan** [comment]
Oi, @lucasmedeiros ! Essa feature estava para ser implementada, mas só finalizei essa semana.

Obrigado pelo feedback! ❤️
