### ISSUE TITLE
Refatorar serviços

### ISSUE THREAD

**Issue by AramisAraujo** [jadsonluan/moodtracker#5]
Olá, estive observando os serviços do teu projeto.
Imagino que num futuro não tão distante (pensando aqui em escalabilidade e manutenibilidade) pode ser bacana dividir as requisições por modelo. Ex: Tags, Moods etc.

**Comment by jadsonluan** [comment]
Obrigado pela sugestão! Implementei nesse [commit](https://github.com/jadsonluan/moodtracker/commit/adfc2dc129230d6598c36728739285e49f17f32f). 🥇
