### ISSUE TITLE
Sugestão: Adicionar loading

### ISSUE THREAD

**Issue by yurikelvin** [jadsonluan/moodtracker#6]
Tenho uma sugestão para o momento quando tu for criar o novo mood, que é adicionar um loading quando a função for chamada pela 1x, evitando que os usuários cliquem novamente enquanto o processamento da 1 chamada estiver sendo realizado... Na prática seria um booleano com useState.

https://github.com/jadsonluan/moodtracker/blob/9170a32fa32de29bd93e5122eacd3c9cfbea49d2/frontend/src/pages/RegisterMoodPage/index.js#L73

**Comment by jadsonluan** [comment]
Resolvido! Obrigado. :)
